export const KARTS = [
  {
    name: 'POPPY',
    label: 'ポピー',
    color: '#f36d49',
    secondary: '#ffe1a1',
    speed: 0.96,
    acceleration: 1.12,
    handling: 1.08,
    tagline: 'どんな道でも、自分のペース。',
    role: 'BALANCED',
  },
  {
    name: 'MINT',
    label: 'ミント',
    color: '#35bba3',
    secondary: '#d8ffd8',
    speed: 0.94,
    acceleration: 1.2,
    handling: 1.16,
    tagline: 'カーブを味方につけよう。',
    role: 'HANDLING',
  },
  {
    name: 'BOLT',
    label: 'ボルト',
    color: '#f6c547',
    secondary: '#fff4d0',
    speed: 1.12,
    acceleration: 0.85,
    handling: 0.89,
    tagline: 'ストレートで、風になる。',
    role: 'SPEED',
  },
  {
    name: 'NOVA',
    label: 'ノヴァ',
    color: '#8b80de',
    secondary: '#eee5ff',
    speed: 1.03,
    acceleration: 1,
    handling: 1,
    tagline: '最後の一周で、星になれ。',
    role: 'ALL-ROUNDER',
  },
  {
    name: 'SKY',
    label: 'スカイ',
    color: '#59abe5',
    secondary: '#e3f4ff',
    speed: 0.98,
    acceleration: 1.16,
    handling: 1.04,
    tagline: '軽やかに、飛び出そう。',
    role: 'ACCELERATION',
  },
  {
    name: 'INK',
    label: 'インク',
    color: '#414b58',
    secondary: '#f7afc6',
    speed: 1.08,
    acceleration: 0.94,
    handling: 0.94,
    tagline: '静かに燃える、挑戦者。',
    role: 'POWER',
  },
];
export const ITEMS = {
  boost: { name: 'ターボ', icon: '⚡', description: '3秒間スピードアップ' },
  rocket: {
    name: 'ロケット',
    icon: '➤',
    description: '前のカートを追いかける',
  },
  mine: { name: 'トラップ', icon: '◆', description: '後方にトラップを設置' },
  shield: { name: 'シールド', icon: '◈', description: '8秒間攻撃をガード' },
  pulse: { name: 'パルス', icon: '✦', description: '近くのライバルをスピン' },
};
export const CPU_NAMES = [
  'Coco',
  'Rio',
  'Luna',
  'Mochi',
  'Ace',
  'Sunny',
  'Pico',
];
export const CUP_POINTS = [15, 12, 10, 8, 6, 4, 2, 1];
