export const KARTS = [
  {
    name: 'POPPY',
    label: 'ポピー',
    color: '#f36d49',
    secondary: '#ffe1a1',
    speed: 0.96,
    acceleration: 1.12,
    handling: 1.08,
    tagline: 'どんな道でも、自分のペース。',
    role: 'BALANCED',
  },
  {
    name: 'MINT',
    label: 'ミント',
    color: '#35bba3',
    secondary: '#d8ffd8',
    speed: 0.94,
    acceleration: 1.2,
    handling: 1.16,
    tagline: 'カーブを味方につけよう。',
    role: 'HANDLING',
  },
  {
    name: 'BOLT',
    label: 'ボルト',
    color: '#f6c547',
    secondary: '#fff4d0',
    speed: 1.12,
    acceleration: 0.85,
    handling: 0.89,
    tagline: 'ストレートで、風になる。',
    role: 'SPEED',
  },
  {
    name: 'NOVA',
    label: 'ノヴァ',
    color: '#8b80de',
    secondary: '#eee5ff',
    speed: 1.03,
    acceleration: 1,
    handling: 1,
    tagline: '最後の一周で、星になれ。',
    role: 'ALL-ROUNDER',
  },
  {
    name: 'SKY',
    label: 'スカイ',
    color: '#59abe5',
    secondary: '#e3f4ff',
    speed: 0.98,
    acceleration: 1.16,
    handling: 1.04,
    tagline: '軽やかに、飛び出そう。',
    role: 'ACCELERATION',
  },
  {
    name: 'INK',
    label: 'インク',
    color: '#414b58',
    secondary: '#f7afc6',
    speed: 1.08,
    acceleration: 0.94,
    handling: 0.94,
    tagline: '静かに燃える、挑戦者。',
    role: 'POWER',
  },
];
export const ITEMS = {
  boost: { name: 'キノコ', icon: '🍄', description: '加速して悪路も突っ切る' },
  triple: {
    name: 'トリプルキノコ',
    icon: '🍄',
    description: '好きなタイミングで3回加速',
  },
  rocket: {
    name: 'アカこうら',
    icon: '🔴',
    description: '前の相手を追尾。長押しで後方をガード',
  },
  green: {
    name: 'ミドリこうら',
    icon: '🟢',
    description: '壁で反射する直進弾。長押しでガード',
  },
  mine: {
    name: 'バナナ',
    icon: '🍌',
    description: '後ろに設置。長押しで後方をガード',
  },
  shield: { name: 'シールド', icon: '◈', description: '8秒間攻撃をガード' },
  pulse: {
    name: 'スーパーホーン',
    icon: '📣',
    description: '周囲の相手・こうらを吹き飛ばす',
  },
  star: {
    name: 'スター',
    icon: '⭐',
    description: '7秒間無敵・加速。体当たりで攻撃',
  },
  lightning: {
    name: 'サンダー',
    icon: '⚡',
    description: '相手全員を小さくしてスピードダウン',
  },
  blue: {
    name: 'トゲこうら',
    icon: '🔵',
    description: '1位を追いかけて周囲ごと爆発',
  },
  bullet: {
    name: 'ロケット',
    icon: '🚀',
    description: '5秒間、無敵で自動走行して追い上げる',
  },
};
export const CPU_NAMES = [
  'Coco',
  'Rio',
  'Luna',
  'Mochi',
  'Ace',
  'Sunny',
  'Pico',
];
export const CUP_POINTS = [15, 12, 10, 8, 6, 4, 2, 1];
